all: false
log-level: info
recursive: true
dir: ./mocks
force-file-write: true
structname: "{{.Mock}}{{.InterfaceName}}"
packages:
  desafiomeli:
    config:
      all: true
      recursive: true
      filename: "{{.InterfaceName}}.go"
      structname: "Mock{{.InterfaceName}}"
      pkgname: "mocks"
